- name: create main directories
  file:
    dest: /jarry/etc/
    mode: 0775
    recurse: yes
    state: directory



- name: insert scriptIP file
  template:
    src: scriptIP.sh.j2
    dest: /jarry/etc/scriptIP.sh
    mode: 0755

- name: insert docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /jarry/etc/docker-compose.yml
    mode: 0755

- name: login to registry
  shell: "docker login {{ service_install_run_registry_url }} -u {{ service_install_run_registry_user }} -p {{ service_install_run_registry_password }}"

- name: run docker-compose
  shell: docker-compose -f /jarry/etc/docker-compose.yml down

- name: run docker-compose
  shell: docker-compose -f /jarry/etc/docker-compose.yml up -d

- name: recuperer l'adresse ip
  shell: def ipPostgres = sh returnStdout: true, script: "/jarry/etc/scriptIP.sh | grep helloworld | awk '{print $1}' | tr -d '\n'"

- name: wait for instance
  uri:
    url: "http://ipPostgres:5000/"
    status_code: 404
  register: result
  until: result.status == 404
  retries: 120
  delay: 1

